<<<<<<< HEAD:payments/migrations/0001_initial.py
# Generated by Django 5.1.4 on 2025-02-05 11:10
=======
# Generated by Django 5.1.4 on 2025-02-03 06:03
>>>>>>> aefe33c2a981346fcdbe67278de9877a517e0ce2:payments/migrations/0001_initial.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:payments/migrations/0001_initial.py
        ('books', '0001_initial'),
=======
        ('books', '0003_book_total_sales'),
>>>>>>> aefe33c2a981346fcdbe67278de9877a517e0ce2:payments/migrations/0001_initial.py
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
