# Generated by Django 5.0.2 on 2025-04-07 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('MYST', 'Mystery'), ('SCI', 'Science'), ('FANT', 'Fantasy'), ('BIO', 'Biography'), ('HIST', 'History'), ('ROM', 'Romance'), ('CHILD', 'Children'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('age_range', models.CharField(choices=[('0-3', '0-3 years'), ('4-7', '4-7 years'), ('8-12', '8-12 years'), ('13-18', '13-18 years'), ('18+', '18+ years')], default='18+', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('stock', models.IntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
