# Generated by Django 5.1.4 on 2025-01-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_book_cover_image_book_slug_book_stock'),
    ]


    operations = [
        migrations.AddField(
            model_name='book',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
