# Generated by Django 5.1.4 on 2025-01-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_image_book_slug_book_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='books.book')),
            ],
        ),
    ]
