# Generated by Django 5.1.4 on 2025-02-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
        ('books', '0003_book_total_sales'),
    ]

    operations = [
    ]
